apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app 
    spec:
      containers:
      - name: app
        image: swathimediboyina/hello-world-0.2-snapshot
        ports:
        - containerPort: 3000
